import { Space_Grotesk } from "next/font/google";
import clsx from "clsx";

import SideNav from "~/components/SideNav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const grotesk = Space_Grotesk({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "text-zinc-400 selection:bg-emerald-200 selection:text-black bg-black relative overflow-x-hidden",
          grotesk.className
        )}
      >
        <SideNav />
        {children}
      </body>
    </html>
  );
}
